### ISSUE TITLE
디버그 모드로 서버를 구동하면~  나오는 메세지

### ISSUE THREAD

**Issue by thomasJang** [axisj/axu4j#34]
```
12:36:08.722 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.tags.DivTag - div#header put to layout#empty.jsp
12:36:08.722 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.DivTag - div#header put to layout#empty.jsp
12:36:08.722 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.tags.DivTag - div#css put to layout#empty.jsp
12:36:08.722 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.DivTag - div#css put to layout#empty.jsp
12:36:08.726 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.tags.DivTag - div#js put to layout#empty.jsp
12:36:08.726 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.DivTag - div#js put to layout#empty.jsp
12:36:08.728 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.config.ConfigReader - create new AXUConfig instance
12:36:08.728 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.config.ConfigReader - create new AXUConfig instance
12:36:08.747 [http-nio-8080-exec-2] ERROR com.axisj.axu4j.tags.ColTag - doTag is fail.
tagBody: null
mustacheHtml: null
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[na:1.8.0_77]
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:100) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005fcol_005f0(login_jsp.java:298) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp.access$8(login_jsp.java:284) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke5(login_jsp.java:416) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke(login_jsp.java:527) [ROOT/:na]
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44) [axu4j-1.0.0-RELEASE.jar:na]
	at com.axisj.axu4j.tags.RowTag.beforeDoTag(RowTag.java:50) [axu4j-1.0.0-RELEASE.jar:na]
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:80) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005frow_005f0(login_jsp.java:279) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp.access$7(login_jsp.java:269) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke4(login_jsp.java:393) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke(login_jsp.java:524) [ROOT/:na]
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44) [axu4j-1.0.0-RELEASE.jar:na]
	at com.axisj.axu4j.tags.DivTag.doTag(DivTag.java:31) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005fdiv_005f3(login_jsp.java:264) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp.access$4(login_jsp.java:252) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke0(login_jsp.java:352) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke(login_jsp.java:512) [ROOT/:na]
	at com.axisj.axu4j.tags.LayoutTag.doTag(LayoutTag.java:57) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005flayout_005f0(login_jsp.java:159) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp._jspService(login_jsp.java:126) [ROOT/:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.33]
	at org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:742) [jasper.jar:8.0.33]
	at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:712) [jasper.jar:8.0.33]
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:111) [ROOT/:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-coyote.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
12:36:08.748 [http-nio-8080-exec-2] ERROR com.axisj.axu4j.tags.RowTag - doTag is fail.
tagBody: null
mustacheHtml: null
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[na:1.8.0_77]
	at com.axisj.axu4j.tags.AXUTagSupport.doTag(AXUTagSupport.java:100) ~[axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005frow_005f0(login_jsp.java:279) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp.access$7(login_jsp.java:269) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke4(login_jsp.java:393) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke(login_jsp.java:524) [ROOT/:na]
	at com.axisj.axu4j.tags.TagUtils.toString(TagUtils.java:44) [axu4j-1.0.0-RELEASE.jar:na]
	at com.axisj.axu4j.tags.DivTag.doTag(DivTag.java:31) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005fdiv_005f3(login_jsp.java:264) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp.access$4(login_jsp.java:252) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke0(login_jsp.java:352) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp$Helper.invoke(login_jsp.java:512) [ROOT/:na]
	at com.axisj.axu4j.tags.LayoutTag.doTag(LayoutTag.java:57) [axu4j-1.0.0-RELEASE.jar:na]
	at org.apache.jsp.axboot.login_jsp._jspx_meth_ax_005flayout_005f0(login_jsp.java:159) [ROOT/:na]
	at org.apache.jsp.axboot.login_jsp._jspService(login_jsp.java:126) [ROOT/:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.33]
	at org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:742) [jasper.jar:8.0.33]
	at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:712) [jasper.jar:8.0.33]
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:111) [ROOT/:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-coyote.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
12:36:08.748 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.tags.DivTag - div#contents put to layout#empty.jsp
12:36:08.748 [http-nio-8080-exec-2] DEBUG com.axisj.axu4j.tags.DivTag - div#scripts put to layout#empty.jsp
12:36:08.861 [http-nio-8080-exec-1] INFO  com.axisj.axu4j.config.ConfigReader - load config from /Users/tom/Works-SI/able-realgrid-axboot/target/axboot-sample-1.0.0/WEB-INF/classes/axu4j.xml
12:36:08.861 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.config.ConfigReader - axu4j.xml
AXUConfig{mode='RUN', layoutPrefix='/layouts/', layoutEncoding='UTF-8', rowWrap='
            
<div id="{{id}}" class="ax-layer {{css}}" style="{{style}}">
	{{{doBody}}}
	<div class="ax-clear"></div>
</div>

        ', colWrap='
            
<div id="{{id}}" class="ax-col-{{size}}">
	<div class="ax-unit">
		<div class="ax-box {{css}}" style="{{style}}">
            {{#wrap}}<div class="ax-box-wrap">{{/wrap}}
                {{{doBody}}}
			{{#wrap}}</div>{{/wrap}}
		</div>
		<div class="ax-clear"></div>
		<div class="H10 DX-H10"></div>
	</div>
</div>

        ', formWrap='
            
<form id="{{id}}" name="{{name}}" method="{{method}}" class="ax-rwd-form {{css}}" style="{{style}}" onsubmit="{{^onsubmit}}return false;{{/onsubmit}}{{onsubmit}}">
	<div class="ax-rwd-table">
		{{{doBody}}}
	</div>
</form>

        ', fieldsWrap='
            
<div id="{{id}}" class="item-group {{class}}" style="{{style}}">
	{{{doBody}}}
	<div class="group-clear"></div>
</div>

        ', fieldWrap='
            

    <div id="{{id}}" class="item {{class}}">
        <div class="item-lable">
{{#labelwidth}}
            <span class="th" style="width:{{labelwidth}};min-width:{{labelwidth}}"><span class="nowrap">{{{label}}}</span></span>
{{/labelwidth}}
{{^labelwidth}}
            <span class="th">{{{label}}}</span>
{{/labelwidth}}
{{#width}}
            <span class="td inputText {{css}}" style="min-width:{{width}};{{style}}" title="{{title}}">
{{/width}}
{{^width}}
            <span class="td inputText {{css}}" style="{{style}}" title="{{title}}">
{{/width}}
                {{{doBody}}}
            </span>
        </div>
    </div>
    <div class="item-clear"></div>

        ', customMap={td=
            
<td class="td-layout" style="{{style}}" rowspan="{{rowspan}}" colspan="{{colspan}}">
	{{{doBody}}}
</td>

        , form-file=
            
<form name={{name}} action="{{action}}" method="{{method}}" enctype="multipart/form-data">
	{{{doBody}}}
</form>

        , select=
            
<select name="{{name}}" id="{{id}}" title="{{title}}" data-ax-path="{{data-ax-path}}" class="{{class}}" style="{{style}}">
{{#emptyName}}
	<option value="">{{emptyName}}</option>
{{/emptyName}}
{{{doBody}}}
{{#options}}
	<option value="{{code}}">{{name}}</option>
{{/options}}
</select>

        , form=
            
<form name={{name}} action="{{action}}" method="{{method}}">
	{{doBody}}
</form>

        , page-button=
            
<div class="ax-button-group cx-common-btns">
    <div class="right">
{{#session.SEARCH_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-search"><i class="axi axi-ion-android-search"></i> ??</button>
{{/session.SEARCH_AUTH}}
{{#session.SAVE_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-save"><i class="axi axi-save"></i> ??</button>
{{/session.SAVE_AUTH}}
{{#session.EXCEL_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-excel"><i class="axi axi-file-excel-o"></i> ??</button>
{{/session.EXCEL_AUTH}}
{{#session.FUNCTION_1_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-fn1"><i class="axi axi-minus-circle"></i> ??</button>
{{/session.FUNCTION_1_AUTH}}
{{#session.FUNCTION_2_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-fn2"><i class="axi axi-plus-circle"></i> ??</button>
{{/session.FUNCTION_2_AUTH}}
{{#session.FUNCTION_3_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-fn3">{{{function3Label}}}</button>
{{/session.FUNCTION_3_AUTH}}
{{#session.FUNCTION_4_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-fn4">{{{function4Label}}}</button>
{{/session.FUNCTION_4_AUTH}}
{{#session.FUNCTION_5_AUTH}}
        <button type="button" class="AXButton Blue" id="ax-page-btn-fn5">{{{function5Label}}}</button>
{{/session.FUNCTION_5_AUTH}}
        {{{doBody}}}
    </div>
    <div class="ax-clear"></div>
</div>

        , table=
            
<table class="ax-tbl-layout">
	{{{doBody}}}
</table>

        , tr=
            
<tr class="{{class}}">
	{{{doBody}}}
</tr>

        }}
12:36:08.877 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.DivTag - div#contents put to layout#empty.jsp
12:36:08.877 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.DivTag - div#scripts put to layout#empty.jsp
12:36:08.877 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.LayoutTag - layout extends /layouts/empty.jsp
12:36:09.076 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.WriteTag - div#js writed
12:36:09.076 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.WriteTag - div#contents writed
12:36:09.076 [http-nio-8080-exec-1] DEBUG com.axisj.axu4j.tags.WriteTag - div#scripts writed
12:36:10.219 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#header put to layout#empty.jsp
12:36:10.219 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#css put to layout#empty.jsp
12:36:10.219 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#js put to layout#empty.jsp
12:36:10.221 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#contents put to layout#empty.jsp
12:36:10.221 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#scripts put to layout#empty.jsp
12:36:10.221 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.LayoutTag - layout extends /layouts/empty.jsp
12:36:10.222 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#js writed
12:36:10.222 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#contents writed
12:36:10.222 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#scripts writed
12:36:11.946 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#header put to layout#base.jsp
12:36:11.946 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#css put to layout#base.jsp
12:36:11.951 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#contents put to layout#base.jsp
12:36:11.951 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.DivTag - div#scripts put to layout#base.jsp
12:36:11.951 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.LayoutTag - layout extends /layouts/base.jsp
12:36:12.062 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#css writed
12:36:12.064 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#ax-header writed
12:36:12.064 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#header writed
12:36:12.064 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#contents writed
12:36:12.064 [http-nio-8080-exec-5] DEBUG com.axisj.axu4j.tags.WriteTag - div#scripts writed
```

**Comment by hyunjun19** [comment]
확인해 보겠습니다~

**Comment by hyunjun19** [comment]
일단 버전을 1.2.0으로 올려보세요.
혹시 버전을 올리면 axu4j.xml이 안 맞을 수도 있으니 그런 경우는 저한테 axu4j.xml을 보내주세요.

**Comment by hyunjun19** [comment]
일단 이 이슈는 패스~!
